"""
DFC2020 with the Copernicus-Bench official 3156/986/986 split.

Why this module exists
----------------------
`dfc2020_official_data_utils.py` splits by held-out city ROI, which is the
honest generalization setting but has two costs: val is a single ROI whose
class distribution is wildly unrepresentative (Chabarovsk is 63% Wetlands, a
class that is 1% of train), so val is useless for model selection; and the
numbers are not comparable to any published benchmark.

Copernicus-Bench (Copernicus-FM, arXiv:2503.11849) defines an official split
over the *same* imagery: it takes the DFC2020 contest set (`ROIs0000_test`,
5128 patches) and randomly partitions it 3156/986/986. Splits are spatially
interleaved -- adjacent patch ids land in different splits -- so val is drawn
from the same distribution as train and test, and results line up with the
published baselines:

    DFC2020-S2 mIoU   supervised ViT-B/16 66.2 | CROMA 66.5 | random init 62.3
    DFC2020-S1 mIoU   supervised ViT-B/16 50.8 | CROMA 52.7 | random init 45.4

Provenance of the file mapping
------------------------------
Copernicus-Bench distributes its own re-encoded copy of the tiles, renamed to
a global patch id (`ROIs0000_test_s2_0_p{N}.tif`) with georeferencing stripped.
The local IEEE DataPort bundle uses per-city ids (`..._s2_{City}_p{N}.tif`) and
the two id spaces are unrelated -- per-city ids are sparse and max out at 1597.

The pixel data is byte-identical between the two, so `cb_patch_map.json` maps
CB patch id -> local filename by md5 of the S2 pixel array. It is generated by
`scripts/build_cobench_map.py`; regenerate it if the local bundle is re-extracted.

Note the local bundle holds 6114 patches = the contest test set (5128, used
here) plus the contest validation set (986, unused by Copernicus-Bench).

Class mapping
-------------
Copernicus-Bench scores **8** classes, not 10: its `cls_mapping` sends
Background(0), Savanna(3) and Snow/Ice(8) to ignore_index. This differs from
`dfc2020_official_data_utils.py`, which scores all 10. To compare against the
published baselines you must use the 8-class mapping, so that is the default
here. Checkpoints are therefore NOT interchangeable between the two modules.
"""

from __future__ import annotations

import json
import random
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader, Subset

from dfc2020_official_data_utils import (
    DFC2020Dataset,
    build_index,
    TaskConfig,
    DFC2020_IGNORE_INDEX,
)

# Copernicus-Bench cls_mapping (cobench_dfc2020s12_wrapper.py):
#   {0:255, 1:0, 2:1, 3:255, 4:2, 5:3, 6:4, 7:5, 8:255, 9:6, 10:7}
# i.e. Background, Savanna and Snow/Ice are ignored; 8 valid classes remain.
COBENCH_CLS_MAPPING = {0: 255, 1: 0, 2: 1, 3: 255, 4: 2, 5: 3,
                       6: 4, 7: 5, 8: 255, 9: 6, 10: 7}
COBENCH_NUM_CLASSES = 8
COBENCH_CLASS_NAMES = ['Forest', 'Shrubland', 'Grassland', 'Wetlands',
                       'Croplands', 'Urban/Built-up', 'Barren', 'Water']

# LUT over raw dfc ids 0-10 -> train ids 0-7 (255 = ignore)
_COBENCH_LUT = np.full(18, DFC2020_IGNORE_INDEX, dtype=np.int64)
for _raw, _tid in COBENCH_CLS_MAPPING.items():
    _COBENCH_LUT[_raw] = _tid

_HERE = Path(__file__).resolve().parent
DEFAULT_MAP = _HERE / 'cb_patch_map.json'
DEFAULT_SPLITS = _HERE / 'cb_splits'


class CoBenchDFC2020Dataset(DFC2020Dataset):
    """DFC2020Dataset with the Copernicus-Bench 8-class label mapping."""

    def __getitem__(self, idx: int) -> dict:
        out = super().__getitem__(idx)
        # super() applied the 10-class mapping (raw-1, 0 -> ignore); undo it by
        # recovering the raw id, then apply the Copernicus-Bench LUT instead.
        mask = out['mask']
        raw = torch.where(mask == DFC2020_IGNORE_INDEX,
                          torch.zeros_like(mask), mask + 1)
        out['mask'] = torch.from_numpy(
            _COBENCH_LUT[raw.numpy().astype(np.int64)]
        )
        return out


def _load_split_ids(splits_dir: Path) -> dict[str, list[str]]:
    """Read the three official CSVs -> {split: [CB dfc filename, ...]}."""
    names = {'train': 'dfc-train-new.csv',
             'val': 'dfc-val-new.csv',
             'test': 'dfc-test-new.csv'}
    out = {}
    for split, fname in names.items():
        path = Path(splits_dir) / fname
        if not path.exists():
            raise FileNotFoundError(
                f'Copernicus-Bench split file missing: {path}. Fetch the three '
                'dfc-*-new.csv files from the l2_dfc2020_s1s2/dfc2020.zip on '
                'HuggingFace (they sit at the head of the archive, so an HTTP '
                'range request is enough -- see scripts/build_cobench_map.py).')
        out[split] = [ln.strip() for ln in path.read_text().splitlines() if ln.strip()]
    return out


def get_dfc2020_loaders(
    batch_size: int = 32,
    num_workers: int = 8,
    data_root: str = 'datasets/DFC2020_official/DFC_Public_Dataset',
    seed: int = 42,
    starting_modality: str = 's2',
    new_modality: str | None = 's1',
    val_fraction: float = 0.0,   # accepted for interface compatibility; unused
    normalize: bool = True,
    target_size: int | None = None,
    patch_map: str | Path = DEFAULT_MAP,
    splits_dir: str | Path = DEFAULT_SPLITS,
) -> tuple:
    """
    Create 5 dataloaders on the Copernicus-Bench official split.

    train (3156) is halved into train1 (stage-0) / train2 (SSL) and val (986)
    into val1 / val2, matching the SHOT interface used by the ROI-disjoint
    loader. test (986) is returned whole.

    Returns:
        train1_loader, val1_loader, train2_loader, val2_loader, test_loader, task_config
    """
    modality_bands_dict = {
        's2':      slice(0, 13),
        's1':      slice(13, 15),
        's2_rgb':   [3, 2, 1],
        's2_norgb': [0, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    }
    assert starting_modality in modality_bands_dict, \
        f"starting_modality must be one of {list(modality_bands_dict)}, got {starting_modality!r}"
    assert new_modality is None or new_modality in modality_bands_dict, \
        f"new_modality must be one of {list(modality_bands_dict)} or None, got {new_modality!r}"

    patch_map = Path(patch_map)
    if not patch_map.exists():
        raise FileNotFoundError(
            f'Patch mapping not found: {patch_map}. Generate it with '
            'scripts/build_cobench_map.py (maps Copernicus-Bench patch ids to '
            'local filenames by S2 pixel hash).')
    cb_to_local = json.loads(patch_map.read_text())
    if 'map' in cb_to_local:           # tolerate the builder's wrapper form
        cb_to_local = cb_to_local['map']

    # local filename (s2 form) -> record
    records = build_index(data_root)
    by_s2name = {Path(r['s2']).name: r for r in records}

    splits = _load_split_ids(Path(splits_dir))
    picked: dict[str, list[dict]] = {}
    missing: dict[str, int] = {}
    for split, fnames in splits.items():
        recs, miss = [], 0
        for f in fnames:
            s2_cb = f.replace('_dfc_', '_s2_')
            local = cb_to_local.get(s2_cb)
            rec = by_s2name.get(local) if local else None
            if rec is None:
                miss += 1
                continue
            recs.append(rec)
        picked[split] = recs
        missing[split] = miss

    if any(missing.values()):
        raise RuntimeError(
            'Could not resolve every Copernicus-Bench patch to a local file '
            f'(unresolved: {missing}). The split would not match the published '
            'benchmark, so refusing to proceed. Regenerate cb_patch_map.json '
            'after confirming the local bundle is fully extracted.')

    ds = lambda recs: CoBenchDFC2020Dataset(recs, target_size=target_size,
                                            normalize=normalize)
    train_ds_full = ds(picked['train'])
    val_ds_full = ds(picked['val'])
    test_ds = ds(picked['test'])

    # halve train -> train1/train2 and val -> val1/val2 (SHOT interface)
    rng = random.Random(seed)
    tr_idx = list(range(len(train_ds_full))); rng.shuffle(tr_idx)
    va_idx = list(range(len(val_ds_full)));   rng.shuffle(va_idx)
    tmid, vmid = len(tr_idx) // 2, len(va_idx) // 2
    train1_ds = Subset(train_ds_full, tr_idx[:tmid])
    train2_ds = Subset(train_ds_full, tr_idx[tmid:])
    val1_ds   = Subset(val_ds_full, va_idx[:vmid])
    val2_ds   = Subset(val_ds_full, va_idx[vmid:])

    print(f'DFC2020 (Copernicus-Bench official split) — '
          f'Train1: {len(train1_ds)}, Train2: {len(train2_ds)}, '
          f'Val1: {len(val1_ds)}, Val2: {len(val2_ds)}, Test: {len(test_ds)}')
    print(f'  {COBENCH_NUM_CLASSES} classes (Savanna/Snow-Ice/Background ignored, '
          f'per Copernicus-Bench cls_mapping)')

    timeout = 120 if num_workers > 0 else 0
    train1_loader = DataLoader(train1_ds, batch_size=batch_size, shuffle=True,
                               num_workers=num_workers, pin_memory=True, timeout=timeout)
    val1_loader   = DataLoader(val1_ds,   batch_size=batch_size, shuffle=False,
                               num_workers=num_workers // 2, pin_memory=True)
    train2_loader = DataLoader(train2_ds, batch_size=batch_size, shuffle=True,
                               num_workers=num_workers, pin_memory=True, timeout=timeout)
    val2_loader   = DataLoader(val2_ds,   batch_size=batch_size, shuffle=False,
                               num_workers=num_workers // 2, pin_memory=True)
    test_loader   = DataLoader(test_ds,   batch_size=batch_size, shuffle=False,
                               num_workers=num_workers // 2, pin_memory=True)

    def _bands_len(spec):
        if isinstance(spec, slice):
            return len(range(*spec.indices(15)))
        return len(spec)

    start_ch = _bands_len(modality_bands_dict[starting_modality])
    new_ch   = _bands_len(modality_bands_dict[new_modality]) if new_modality is not None else 0
    img_size = int(test_ds[0]['image'].shape[-1])

    task_config = TaskConfig(
        dataset_name='dfc2020',
        task_type='segmentation',
        modality_a=starting_modality,
        modality_b=new_modality,
        modality_a_channels=start_ch,
        modality_b_channels=new_ch,
        num_classes=COBENCH_NUM_CLASSES,
        multilabel=False,
        label_key='mask',
        modality_bands_dict=modality_bands_dict,
        img_size=img_size,
        ignore_index=DFC2020_IGNORE_INDEX,
    )
    return train1_loader, val1_loader, train2_loader, val2_loader, test_loader, task_config
