#!/bin/bash
# All DFC2020 / Copernicus-Bench baselines, upernet decoder, current teachers.
#
# Families
#   distillation  teacher-based, multimodal student  (teacher -> student pair)
#   mke           teacher-based, multimodal student  (multimodal knowledge expansion)
#   freematch     semi-supervised, single modality   (no teacher)
#   mixmatch      semi-supervised, single modality   (no teacher)
#
# Teachers come from artifacts/sft_teachers.json under the
# "dfc2020_cobench/<modality>/<model>/<decoder>" key, regenerated by
# res/train_sft/sft_best.py. DECODER must match the teacher: an upernet teacher
# with a linear student is not a like-for-like comparison (~10 mIoU apart).
#
# Usage:
#   bash sh/baselines_dfc2020_cobench.sh            # dry run, prints the plan
#   SUBMIT=1 bash sh/baselines_dfc2020_cobench.sh   # actually sbatch
#   DECODER=linear SUBMIT=1 bash ...                # linear arm instead

set -u
DECODER="${DECODER:-upernet}"
MODEL="${MODEL:-evan_base}"
EPOCHS="${EPOCHS:-64}"
LRS="${LRS:-0.0005 0.0001}"
# KD variants for the distillation baseline (MKE has no such knob).
KL_TYPES="${KL_TYPES:-kd ttm}"
SUBMIT="${SUBMIT:-0}"
TEACHERS_JSON="artifacts/sft_teachers.json"
TEACHER_SPLIT="${TEACHER_SPLIT:-split1}"

SINGLES="s1 s2_rgb s2_norgb"
# teacher -> new modality, both orderings (the delulu directions)
PAIRS="s1:s2_rgb s1:s2_norgb s2_rgb:s1 s2_rgb:s2_norgb s2_norgb:s1 s2_norgb:s2_rgb"

n=0
submit () {  # $1=name  $2...=args
    local tag="$1"; shift
    if [ "$SUBMIT" = "1" ]; then
        sbatch --export=ALL,BASELINE_ARGS="$*",RUN_TAG="${tag}",DECODER="${DECODER}" \
            sh/baselines_dfc2020_job.sh >/dev/null
    fi
    echo "  [$((++n))] ${tag}"
}

echo "=== teacher-based: distillation + mke (6 directions x ${DECODER}) ==="
for P in ${PAIRS}; do
    START="${P%%:*}"; NEW="${P##*:}"
    # split1 teacher: these baselines use train2 as the unlabeled pool, so a
    # `full` teacher would already have been supervised on it (see
    # res/train_sft/README_dfc2020.md, "Teacher train_split leak").
    TEACHER=$(jq -r ".\"dfc2020_cobench/${START}/${MODEL}/${DECODER}/${TEACHER_SPLIT}\".checkpoint // empty" "${TEACHERS_JSON}")
    if [ -z "${TEACHER}" ] || [ ! -f "${TEACHER}" ]; then
        echo "  [skip] no ${DECODER}/${TEACHER_SPLIT} teacher for ${START}"; continue
    fi
    for LR in ${LRS}; do
        for KL in ${KL_TYPES}; do
            submit "distillation_${KL}_${START}_to_${NEW}_lr${LR}" \
                "baseline/baseline_distillation.py --dataset dfc2020 --modalities ${START} ${NEW}" \
                "--teacher_checkpoint ${TEACHER} --decoder_type ${DECODER} --model ${MODEL}" \
                "--epochs ${EPOCHS} --lr ${LR} --kl_type ${KL}" \
                "--results_csv res/baselines/dfc2020_cobench_distillation_${DECODER}.csv"
        done
        submit "mke_${START}_to_${NEW}_lr${LR}" \
            "baseline/baseline_mke.py --dataset dfc2020 --modalities ${START} ${NEW}" \
            "--teacher_checkpoint ${TEACHER} --decoder_type ${DECODER} --model ${MODEL}" \
            "--epochs ${EPOCHS} --lr ${LR}" \
            "--results_csv res/baselines/dfc2020_cobench_mke_${DECODER}.csv"
    done
done

echo "=== semi-supervised: freematch + mixmatch (3 single modalities x ${DECODER}) ==="
for M in ${SINGLES}; do
    for LR in ${LRS}; do
        for B in freematch mixmatch; do
            submit "${B}_${M}_lr${LR}" \
                "baseline/baseline_${B}.py --dataset dfc2020 --modality ${M}" \
                "--decoder_type ${DECODER} --model ${MODEL} --use_dino_weights" \
                "--epochs ${EPOCHS} --lr ${LR}" \
                "--results_csv res/baselines/dfc2020_cobench_${B}_${DECODER}.csv"
        done
    done
done

echo
echo "total: ${n} jobs (SUBMIT=${SUBMIT})"
