"""MixMatch Semi-Supervised Baseline (Berthelot et al., NeurIPS 2019).

Uses train_split1 as labeled data and train_split2 as unlabeled data.
Pseudo-labels are generated by averaging K weak-augmented views and sharpening
with temperature T, then mixing labeled+unlabeled via MixUp (alpha=0.75).
Loss = soft-CE (labeled) + lambda_u * MSE (unlabeled). No thresholding.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import torch
import torch.nn as nn
import torch.nn.functional as F
import logging
import argparse
from datetime import datetime
import wandb
import csv
from tqdm import tqdm
import kornia.augmentation as K

from evan_main import evan_small, evan_base, evan_large, evan_small_s2, BENV2_BAND_INDICES, PASTIS_BAND_INDICES, EVANClassifier, EvanSegmenter
from data_utils import get_loaders, create_multimodal_batch
from train_utils import evaluate

VALID_MODALITIES = {
    'eurosat': ['rgb', 'vre', 'nir', 'swir'],
    'benv2':   ['s1', 's2', 's2_rgb'],
    'pastis':  ['s1', 's2', 'rgb'],
    'dfc2020': ['s1', 's2', 's2_rgb'],
}

logging.basicConfig(level=logging.INFO, format='%(name)s - %(levelname)s - %(message)s')


# ---------------------------------------------------------------------------
# Augmentation factory
# ---------------------------------------------------------------------------

def make_weak_augmentation():
    """Weak augmentation: random flips only (channel-agnostic)."""
    return K.AugmentationSequential(
        K.RandomHorizontalFlip(p=0.5),
        K.RandomVerticalFlip(p=0.5),
        data_keys=["input"],
    )


# ---------------------------------------------------------------------------
# Helper: get task config and loaders
# ---------------------------------------------------------------------------

def _n_chans(entry) -> int:
    if isinstance(entry, slice):
        return entry.stop - entry.start
    return len(entry)


def get_task_config_and_loaders(dataset, modality, batch_size, num_workers,
                                data_normalizer=None, num_time_steps=10):
    train1, val1, train2, val2, test, task_config = get_loaders(
        dataset, modality, batch_size, num_workers,
        data_normalizer=data_normalizer, num_time_steps=num_time_steps,
    )
    return train1, val1, train2, val2, test, task_config


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='MixMatch Semi-Supervised Baseline')
    parser.add_argument('--dataset', type=str, required=True,
                        choices=['eurosat', 'benv2', 'pastis', 'dfc2020'])
    parser.add_argument('--modality', type=str, required=True,
                        help='Modality to train on (single modality)')
    parser.add_argument('--model', type=str, default='evan_small',
                        choices=['evan_small', 'evan_base', 'evan_large'])
    parser.add_argument('--use_dino_weights', action='store_true',
                        help='Init EVAN backbone from DINOv2 ViT weights')
    parser.add_argument('--batch_size', type=int, default=32)
    parser.add_argument('--lr', type=float, default=1e-4)
    parser.add_argument('--weight_decay', type=float, default=1e-4)
    parser.add_argument('--epochs', type=int, default=10)
    parser.add_argument('--num_workers', type=int, default=4)
    parser.add_argument('--num_time_steps', type=int, default=10,
                        help='Timestamps per PASTIS image (default: 10)')
    parser.add_argument('--tz_fusion_time', type=int, default=3)
    parser.add_argument('--tz_lora_rank', type=int, default=0)
    parser.add_argument('--tz_modality_specific_layer_augmenter', type=str, default='fft',
                        choices=['fft'])
    parser.add_argument('--checkpoint_dir', type=str, default='checkpoints')
    parser.add_argument('--wandb_project', type=str, default='mixmatch')
    parser.add_argument('--global_rep', type=str, default='clstoken',
                        choices=['clstoken', 'mean_patch'])
    parser.add_argument('--train_mode', type=str, default='fft',
                        choices=['probe', 'adaptor', 'fft', 'emb+probe'])
    parser.add_argument('--checkpoint_name', type=str, default=None)
    parser.add_argument('--val_per_epoch', type=int, default=1)
    parser.add_argument('--warmup_epochs', type=int, default=1)
    parser.add_argument('--results_csv', type=str, default=None)
    # MixMatch-specific
    parser.add_argument('--K', type=int, default=2,
                        help='Number of augmented views for label guessing (default: 2)')
    parser.add_argument('--temperature', type=float, default=0.5,
                        help='Sharpening temperature for pseudo-labels (default: 0.5)')
    parser.add_argument('--alpha', type=float, default=0.75,
                        help='Beta distribution parameter for MixUp (default: 0.75)')
    parser.add_argument('--lambda_u', type=float, default=75.0,
                        help='Max unsupervised loss weight; ramped from 0 over warmup_epochs (default: 75.0)')
    parser.add_argument('--mixmatch_warmup_epochs', type=int, default=4,
                        help='Epochs over which lambda_u is linearly ramped per-step to its max value (default: 4)')
    args = parser.parse_args()

    # Validate modality
    valid_mods = VALID_MODALITIES[args.dataset]
    if args.modality not in valid_mods:
        parser.error(f"--modality {args.modality!r} not valid for {args.dataset}. "
                     f"Valid: {valid_mods}")

    if args.results_csv is None:
        args.results_csv = f"res/baseline_mixmatch_{args.dataset}.csv"

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Dataset: {args.dataset}, Modality: {args.modality}")
    print(f"Using device: {device}")

    # Data
    print("\n=== Creating datasets ===")
    train1, val1, train2, val2, test, task_config = get_task_config_and_loaders(
        args.dataset, args.modality, args.batch_size, args.num_workers,
        num_time_steps=args.num_time_steps,
    )
    modality_bands_dict = task_config.modality_bands_dict
    num_chans = _n_chans(modality_bands_dict[args.modality])

    is_segmentation = (task_config.task_type == 'segmentation')
    multilabel = task_config.multilabel
    metric_name = "mIoU" if is_segmentation else ("mAP" if multilabel else "Acc")

    print(f"  train1 (labeled): {len(train1.dataset)} samples")
    print(f"  train2 (unlabeled): {len(train2.dataset)} samples")
    print(f"  Modality: {args.modality} ({num_chans} channels)")
    print(f"  Task: {task_config.task_type}, Metric: {metric_name}")

    # Model (mirrors baseline_freematch.py)
    print("\n=== Creating EVAN model ===")
    common_kwargs = dict(
        tz_fusion_time=args.tz_fusion_time,
        tz_lora_rank=args.tz_lora_rank,
        tz_modality_specific_layer_augmenter=args.tz_modality_specific_layer_augmenter,
        n_storage_tokens=4,
        starting_modality=args.modality,
        starting_n_chans=num_chans,
        img_size=task_config.img_size,
        device=device,
    )
    model_fn = {'evan_small': evan_small, 'evan_base': evan_base, 'evan_large': evan_large}[args.model]
    evan = model_fn(load_weights=args.use_dino_weights, **common_kwargs)

    if is_segmentation:
        model = EvanSegmenter(
            evan, num_classes=task_config.num_classes,
            decoder_strategy="mean", device=device,
        )
    else:
        model = EVANClassifier(
            evan, num_classes=task_config.num_classes,
            classifier_strategy="mean", global_rep=args.global_rep, device=device,
        )
    model = model.to(device)

    # Freeze/unfreeze (mirrors baseline_freematch.py)
    model.freeze_all()
    if args.train_mode == 'fft':
        model.set_requires_grad('backbone', blocks=True, norm=True)
        model.set_requires_grad('all', patch_embedders=True, clsreg=True, msla=True,
                                modality_encoders=True, head=True)
        print("Mode=fft: training full backbone layers + head.")
    elif args.train_mode == 'adaptor':
        model.set_requires_grad(args.modality, patch_embedders=True, clsreg=True,
                                msla=True, mfla=True, head=True)
        print("Mode=adaptor: training embedder, adaptors and head.")
    elif args.train_mode == 'probe':
        model.set_requires_grad('all', head=True)
        print("Mode=probe: training head only.")
    elif args.train_mode == 'emb+probe':
        model.set_requires_grad('all', patch_embedders=True, head=True)
        print("Mode=emb+probe: training embedder + head.")

    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    print(f"Trainable: {trainable_params:,} / {total_params:,} ({100*trainable_params/total_params:.2f}%)")

    # Optimizer
    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=args.lr, weight_decay=args.weight_decay,
    )

    # Wandb
    if args.wandb_project:
        wandb.init(
            project=args.wandb_project,
            config=vars(args),
            name=f"mixmatch_{args.dataset}_{args.modality}_{args.train_mode}",
        )

    # Augmentation (weak only — MixMatch does not use strong aug)
    weak_aug = make_weak_augmentation()

    # Checkpoint path
    os.makedirs(args.checkpoint_dir, exist_ok=True)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    if args.checkpoint_name:
        checkpoint_path = os.path.join(args.checkpoint_dir, f'{args.checkpoint_name}.pt')
    else:
        checkpoint_path = os.path.join(
            args.checkpoint_dir,
            f'evan_mixmatch_{args.dataset}_{args.modality}_{timestamp}.pt',
        )

    # Train
    print(f"\n=== MixMatch training for {args.epochs} epochs ===")
    print(f"  K={args.K}, temperature={args.temperature}, alpha={args.alpha}, "
          f"lambda_u={args.lambda_u}, mixmatch_warmup_epochs={args.mixmatch_warmup_epochs}")

    from train_utils import Trainer
    trainer = Trainer(
        model, optimizer, device, task_config,
        clip_norm=10.0,
        use_wandb=bool(args.wandb_project),
        wandb_prefix='mixmatch',
        warmup_epochs=args.warmup_epochs,
    )

    train_metric, test_metric, best_val_metric, best_val_test_metric = trainer.train_mixmatch(
        train1_loader=train1,
        train2_loader=train2,
        val1_loader=val1,
        test_loader=test,
        num_epochs=args.epochs,
        modality=args.modality,
        weak_aug=weak_aug,
        K=args.K,
        temperature=args.temperature,
        alpha=args.alpha,
        lambda_u=args.lambda_u,
        warmup_epochs=args.mixmatch_warmup_epochs,
        best_checkpoint_path=checkpoint_path,
        val_per_epoch=args.val_per_epoch,
    )

    print(f"\n=== MixMatch training complete ===")
    print(f"  Train {metric_name}: {train_metric:.2f}%")
    print(f"  Test  {metric_name}: {test_metric:.2f}%")
    if best_val_metric is not None:
        print(f"  Best val {metric_name}: {best_val_metric:.2f}%")
        print(f"  Best val→test {metric_name}: {best_val_test_metric:.2f}%")

    # CSV
    filename = args.results_csv
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    file_exists = os.path.isfile(filename)
    fieldnames = [
        "model_type", "modality", "train_mode", "learning_rate", "weight_decay",
        "trainable_params", "epochs", "K", "temperature", "alpha",
        "lambda_u", "mixmatch_warmup_epochs", "metric_name",
        "test_metric", "best_val_metric", "best_val_test_metric",
        "saved_checkpoint", "global_rep", "use_dino_weights",
    ]
    with open(filename, mode='a', newline='') as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(fieldnames)
        writer.writerow([
            args.model, args.modality, args.train_mode, args.lr, args.weight_decay,
            trainable_params, args.epochs, args.K, args.temperature, args.alpha,
            args.lambda_u, args.mixmatch_warmup_epochs, metric_name,
            f"{test_metric:.2f}",
            f"{best_val_metric:.2f}" if best_val_metric is not None else "",
            f"{best_val_test_metric:.2f}" if best_val_test_metric is not None else "",
            checkpoint_path, args.global_rep, args.use_dino_weights,
        ])
    print(f"Results appended to {filename}")

    if args.wandb_project:
        wandb.finish()
    return checkpoint_path


if __name__ == '__main__':
    main()


# DRYRUN examples
"""
# EuroSAT RGB (classification)
python -u baseline/baseline_mixmatch.py --dataset eurosat --modality rgb --epochs 5 --use_dino_weights

# BEN-v2 S2 (multilabel)
python -u baseline/baseline_mixmatch.py --dataset benv2 --modality s2 --epochs 5

# DFC2020 S2 (segmentation)
python -u baseline/baseline_mixmatch.py --dataset dfc2020 --modality s2 --epochs 5
"""
